/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(LMS_postdistorter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d220f2b07c65f81ee2103997babe61df)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dpd/LMS_postdistorter.h>
// pydoc.h is automatically generated in the build directory
#include <LMS_postdistorter_pydoc.h>

void bind_LMS_postdistorter(py::module& m)
{

    using LMS_postdistorter = gr::dpd::LMS_postdistorter;


    py::class_<LMS_postdistorter,
               gr::block,
               gr::basic_block,
               std::shared_ptr<LMS_postdistorter>>(
        m, "LMS_postdistorter", D(LMS_postdistorter))

        .def(py::init(&LMS_postdistorter::make),
             py::arg("dpd_params"),
             py::arg("iter_limit"),
             py::arg("method"),
             py::arg("learning_rate"),
             D(LMS_postdistorter, make))


        ;
}
