/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(MP_model_PA.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(97cd6aae58ebe02cb79376a9df98a718)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dpd/MP_model_PA.h>
// pydoc.h is automatically generated in the build directory
#include <MP_model_PA_pydoc.h>

void bind_MP_model_PA(py::module& m)
{

    using MP_model_PA = gr::dpd::MP_model_PA;


    py::class_<MP_model_PA, gr::block, gr::basic_block, std::shared_ptr<MP_model_PA>>(
        m, "MP_model_PA", D(MP_model_PA))

        .def(py::init(&MP_model_PA::make),
             py::arg("Order"),
             py::arg("Mem_Depth"),
             py::arg("Mode"),
             py::arg("Coeff"),
             D(MP_model_PA, make))


        ;
}
