/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(predistorter_training.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(25639ba957cc20123e71518f665fca22)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dpd/predistorter_training.h>
// pydoc.h is automatically generated in the build directory
#include <predistorter_training_pydoc.h>

void bind_predistorter_training(py::module& m)
{

    using predistorter_training    = gr::dpd::predistorter_training;


    py::class_<predistorter_training, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<predistorter_training>>(m, "predistorter_training", D(predistorter_training))

        .def(py::init(&predistorter_training::make),
           D(predistorter_training,make)
        )
        



        ;




}








